In [1]:
import numpy as np
import random

In [11]:
# Lignes - Colonnes
# Row (ligne) major comme C++ 
# [0, 100[ - https://numpy.org/doc/stable/reference/random/index.html#random-quick-start                                             
A = np.random.randint(0, 100, [5,5])  
print(A) 
print(A.shape)          # tuple avec la taille de chaque dimension
print(A.ndim)           # le nb de dimensions
print(A.size)           # le nb de cellule


[[53 69 31 19 97]
 [75 45 94 57 93]
 [ 2 87 68 76 30]
 [37 31 76  1 50]
 [61 73  4 87 95]]
(5, 5)
2
25


In [10]:
A = np.array([0, 1, 2, 3])                # 1D et 4 ele
print(A)
print()

B = np.array([1,2,3]).reshape(3,1)        # Z! Important                     
print(B)
print()
B = B.squeeze()                           # (3, 1) -> (3, )
print(B)
print()

C = np.array([i for i in range(100, 109)]).reshape(3,3)
print(C)
print()

# Construit un Dataset (dico) de 10 expériences avec 3 valeurspts chacunes
Dataset = {f"Experience {i}" : np.random.randn(3) for i in range(10)} 
print(Dataset)
print()

# 3 lignes, 4 col avec des valeurs entre 0 et 1
# n comme normalized 
# y a aussi un np.random.seed(0)
D = np.random.randn(3,4)                    
print(D)

[0 1 2 3]

[[1]
 [2]
 [3]]

[1 2 3]

[[100 101 102]
 [103 104 105]
 [106 107 108]]

{'Experience 0': array([1.1730845 , 0.48419163, 0.50186945]), 'Experience 1': array([0.90879781, 0.37023261, 0.39293042]), 'Experience 2': array([1.1316552 , 1.44137279, 0.14150722]), 'Experience 3': array([-1.07993141,  0.41610611,  0.9973634 ]), 'Experience 4': array([-0.87480093,  0.852543  , -0.44147719]), 'Experience 5': array([ 1.21944838, -1.5842851 , -0.6202762 ]), 'Experience 6': array([1.60237982, 1.21003658, 0.41238789]), 'Experience 7': array([0.38454473, 1.17394849, 0.65581362]), 'Experience 8': array([-0.27728427, -0.25508762,  1.84503144]), 'Experience 9': array([-0.80433396,  0.43787014, -1.21604578])}

[[-0.16811216  0.28209108  0.30996845  1.4964755 ]
 [ 1.16911256  0.82003169  0.33280388  0.12656524]
 [ 1.53987703  0.51497908 -0.86048719 -0.47074262]]


In [14]:
# matrice identité 4x4
MyTab = np.eye(4)     
print(MyTab)
print()

MyTab = np.ones((3,2)) # passer un tuple
print(MyTab)
print()

MyTab = np.zeros((3,2))                   
print(MyTab)
print()




[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]



In [16]:
# 100 points entre [10 et 20]
F = np.linspace(10, 20, 100)   
print(F)
print()            

# n points entre [10 et 20[ au pas de .7  
G = np.arange(10, 20, .7, dtype=np.float16)
print(G)
print()

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

In [26]:
Tab1 = np.random.randn(3, 3) 
print(Tab1)
print()

Tab2 = np.eye(3, 3) 
print(Tab2)
print()

# axis = 0 => vertical
Tab5 = np.concatenate((Tab1, Tab2), axis=0)
print(Tab5)
print()

# axis = 1 => horizontal   
Tab6 = np.concatenate((Tab1, Tab2), axis=1) 
print(Tab6)
print()

Tab7 = Tab6.reshape(9, 2) 
print(Tab7)
print()

[[-0.74798541 -0.10339651  0.5202796 ]
 [-1.18914663  0.00878388  0.50910167]
 [ 0.23587011  0.52199622  0.36530682]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[-0.74798541 -0.10339651  0.5202796 ]
 [-1.18914663  0.00878388  0.50910167]
 [ 0.23587011  0.52199622  0.36530682]
 [ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.          1.        ]]

[[-0.74798541 -0.10339651  0.5202796   1.          0.          0.        ]
 [-1.18914663  0.00878388  0.50910167  0.          1.          0.        ]
 [ 0.23587011  0.52199622  0.36530682  0.          0.          1.        ]]

[[-0.74798541 -0.10339651]
 [ 0.5202796   1.        ]
 [ 0.          0.        ]
 [-1.18914663  0.00878388]
 [ 0.50910167  0.        ]
 [ 1.          0.        ]
 [ 0.23587011  0.52199622]
 [ 0.36530682  0.        ]
 [ 0.          1.        ]]



In [28]:
# transforme en tableau 1D. 
# Utile pour 
#    les spectres d'images 
#    les images en entrée de réseau de neurones
#    optimize.minimize (x0)
Tab1 = np.random.randn(2, 2) 
print(Tab1)
print()

Tab2 = Tab1.ravel()   
print(Tab2)
print()


[[ 0.30672516 -0.11726129]
 [-0.10063835 -1.43442927]]

[ 0.30672516 -0.11726129 -0.10063835 -1.43442927]



In [29]:
X = np.random.randn(3, 4)
print(X)
print()
X[:,-1:] = 1           # met des 1 dans la dernière colonne
print(X)
print

[[ 0.22641225  0.05130817  0.33127517  0.16916666]
 [ 1.09125223 -0.14177761 -1.44419525  1.16691396]
 [ 0.55443991 -0.60935397  0.6704893  -0.84635889]]

[[ 0.22641225  0.05130817  0.33127517  1.        ]
 [ 1.09125223 -0.14177761 -1.44419525  1.        ]
 [ 0.55443991 -0.60935397  0.6704893   1.        ]]


<function print>

In [2]:
A = np.random.randn(3, 3) 
print (f"Matrice 3x3 :")
print(A)
print()

# slicing A[debut:fin:pas, debut:fin:pas]
print(A)
print()
print("Colonne 0 : ", A[:, 0])
print()

print(A)
print("Colonne 2 : ", A[:, 2])
print()

print(A)
print()
print("Ligne 1   : ", A[1, :])
print()

print(A)
print()
print("Ligne 2   : ", A[2])                   
print()


Matrice 3x3 :
[[-0.44005747  0.4779577  -0.27853577]
 [-0.83849533  0.56884896 -0.06397348]
 [ 0.54772505 -1.05278659 -1.49641234]]

[[-0.44005747  0.4779577  -0.27853577]
 [-0.83849533  0.56884896 -0.06397348]
 [ 0.54772505 -1.05278659 -1.49641234]]

Colonne 0 :  [-0.44005747 -0.83849533  0.54772505]

[[-0.44005747  0.4779577  -0.27853577]
 [-0.83849533  0.56884896 -0.06397348]
 [ 0.54772505 -1.05278659 -1.49641234]]
Colonne 2 :  [-0.27853577 -0.06397348 -1.49641234]

[[-0.44005747  0.4779577  -0.27853577]
 [-0.83849533  0.56884896 -0.06397348]
 [ 0.54772505 -1.05278659 -1.49641234]]

Ligne 1   :  [-0.83849533  0.56884896 -0.06397348]

[[-0.44005747  0.4779577  -0.27853577]
 [-0.83849533  0.56884896 -0.06397348]
 [ 0.54772505 -1.05278659 -1.49641234]]

Ligne 2   :  [ 0.54772505 -1.05278659 -1.49641234]



In [5]:
A = np.random.randn(3, 3) 

# subseting. /!\ de 0 à 2 exclu
print(A)
print()
print("subseting. /!\ de 0 à 2 exclu")
B = A[0:2, 0:2]   
print(B)
print()

# Initialise une sous-partie de la matrice
print(A)
print()
print("Initialise une sous-partie de la matrice")
A[0:2, 0:2] = 3.14  
print(A)
print()

# copier les 2 dernières colonnes
print(A)
print()
print("copier les 2 dernières colonnes")
D = A[:,-2:]
print(D)
print()



[[-0.94325467  0.97698517 -0.23986991]
 [ 0.18349751 -0.54183462  0.90999597]
 [-0.08684661  0.47352754 -0.52180052]]

subseting. /!\ de 0 à 2 exclu
[[-0.94325467  0.97698517]
 [ 0.18349751 -0.54183462]]

[[-0.94325467  0.97698517 -0.23986991]
 [ 0.18349751 -0.54183462  0.90999597]
 [-0.08684661  0.47352754 -0.52180052]]

Initialise une sous-partie de la matrice
[[ 3.14        3.14       -0.23986991]
 [ 3.14        3.14        0.90999597]
 [-0.08684661  0.47352754 -0.52180052]]

[[ 3.14        3.14       -0.23986991]
 [ 3.14        3.14        0.90999597]
 [-0.08684661  0.47352754 -0.52180052]]

copier les 2 dernières colonnes
[[ 3.14       -0.23986991]
 [ 3.14        0.90999597]
 [ 0.47352754 -0.52180052]]

[[ 3.14        3.14       -0.23986991]
 [ 3.14        3.14        0.90999597]
 [-0.08684661  0.47352754 -0.52180052]]

insérer un damier de 1
[[1.         3.14       1.        ]
 [3.14       3.14       0.90999597]
 [1.         0.47352754 1.        ]]

[[  1.         100.           

In [11]:
A = np.random.randn(3, 3) 

# insérer un damier de 1 
print(A)
print()
E = A 
print("insérer un damier de 1")
E[::2, ::2] = 1     
print(E)
print()

# mettre à 0 selon condition
A = np.random.randint(0, 100, [5, 5]) 
print(A)
print()

print("Met à 0 si val inf à 20 OU val sup à 80")
A[(A<20) | (A>80)] = 0  
print(A)
print()



[[-1.90787622 -0.70466858 -0.61021942]
 [-1.09318903 -0.72615854  0.50912354]
 [ 0.2613719  -1.09160318  0.00214481]]

insérer un damier de 1
[[ 1.         -0.70466858  1.        ]
 [-1.09318903 -0.72615854  0.50912354]
 [ 1.         -1.09160318  1.        ]]

[[73 40 43 61 94]
 [ 6 70 22 30 46]
 [29 57 91 52 78]
 [66 78 87 62 62]
 [ 3 83 36  4 48]]

Met à 0 si val inf à 20 OU val sup à 80
[[73 40 43 61  0]
 [ 0 70 22 30 46]
 [29 57  0 52 78]
 [66 78  0 62 62]
 [ 0  0 36  0 48]]



In [21]:
# Filtrage
A = np.random.randint(0, 10, [5, 5])
print(A)
print(A.ndim)           
print(A.shape)          

print()

# A n'est plus une matrice mais un vecteur!
print ("La matrice est devenue un vecteur dont les valeurs sont inf à 5")
A = A[A<5]                                   
print(A)
print(A.ndim)           
print(A.shape)          
print()



[[6 7 6 8 8]
 [9 6 4 0 9]
 [1 6 5 9 3]
 [5 4 1 1 8]
 [2 5 7 9 7]]
2
(5, 5)

La matrice est devenue un vecteur dont les valeurs sont inf à 5
[4 0 1 3 4 1 1 2]
1
(8,)



In [26]:
A = np.random.randint(0,10, [5,5])
print("Matrice A : \n", A)
print()

B = np.random.randn(5, 5)
print(f"Matrice B :\n {B}", )
print()

C = B[A<2]                                # on applique à B le filtre A < 2
print(f"Vecteur qui ne retient de B que les valeurs filtrées suivant 'Val<2' appliqué à A:")
print(f"{C}\n")
  

Matrice A : 
 [[1 3 6 8 1]
 [1 6 8 2 7]
 [9 9 6 3 4]
 [8 6 6 9 1]
 [6 3 2 3 0]]

Matrice B :
 [[ 0.72790594 -0.12322369  0.11560007 -0.08114708 -0.83476687]
 [ 1.22206688  0.10715518  0.16838814  0.3241939  -0.468784  ]
 [-0.64867714 -1.23889137  1.26820992 -1.25109156  1.91779441]
 [ 1.20815591 -0.52496718  0.71123522  1.01597898 -0.26924885]
 [-0.11237434 -0.63765668  0.95553879 -0.55164505 -1.0669719 ]]

Vecteur qui ne retient de B que les valeurs filtrées selon le 'Val<2' appliqué à A:
[ 0.72790594 -0.83476687  1.22206688 -0.26924885 -1.0669719 ]



In [32]:
A = np.random.randint(0, 10, (3, 5))
print(A)
print()

# somme de tous les éléments
print("Somme de tous les éléments :")
print(A.sum())
print()                            

# un vecteur de col éléments. Somme selon chaque colonne
print("Un vecteur de 'colonnes' éléments contenant la somme de chaque colonne :")
print(A.sum(axis=0))
print()                             

# un vecteur de A.size élé
# contient la somme cumulée en row major (ligne à ligne)
print("Un vecteur de 'A.size()' éléments contenant la somme cumulée :")
print(A.cumsum())
print()

# Une matrice. 
# Sur chaque ligne, somme cumulée le long des colonnes
print("Une matrice avec sur chaque ligne, la somme cumulée le long des colonnes")
print(A.cumsum(axis=1))
print()

# un vecteur avec la position des minimums dans les colonnes
print("Un vecteur avec la position des minimums dans les colonnes")
print(A.argmin(axis=0))
print()                          

# une matrice de même dimension que A. Contient les indices
# pour trier sur chaque ligne, selon les colonnes 
print("Une matrice de même dimension que A")
print("Contient les indices pour trier sur chaque ligne, selon les colonnes")
print(A.argsort(axis=1))
print()                         




[[6 0 7 6 2]
 [7 3 0 5 6]
 [2 4 7 3 6]]

Somme de tous les éléments :
64

Un vecteur de 'colonnes' éléments contenant la somme de chaque colonne :
[15  7 14 14 14]

Un vecteur de 'A.size()' éléments contenant la somme cumulée :
[ 6  6 13 19 21 28 31 31 36 42 44 48 55 58 64]

Une matrice avec sur chaque ligne, la somme cumulée le long des colonnes
[[ 6  6 13 19 21]
 [ 7 10 10 15 21]
 [ 2  6 13 16 22]]

Un vecteur avec la position des minimums dans les colonnes
[2 0 1 2 0]

Une matrice de même dimension que A
Contient les indices pour trier sur chaque ligne, selon les colonnes
[[1 4 0 3 2]
 [2 1 3 4 0]
 [0 3 1 4 2]]



array([5.        , 2.33333333, 4.66666667, 4.66666667, 4.66666667])

In [33]:
A = np.random.randint(0, 10, (3, 5))
print(A)
print()

print("Moyenne des valeurs de la matrice")
print(A.mean())
print()

# moyenne des colonnes
print("Moyenne de chaque colonne")
print(A.mean(axis=0))                            
print()

[[7 8 2 0 7]
 [7 4 3 5 5]
 [7 8 4 0 6]]

Moyenne des valeurs de la matrice
4.866666666666666

Moyenne de chaque colonne
[7.         6.66666667 3.         1.66666667 6.        ]



# À mettre sous forme de mini cellule

In [9]:


                                            





A = np.exp(A
# Matrice des coefs de correlation entre les lignes de A
np.corrcoef(A)                            
# Coef de correlation entre les lignes 0 et 1 de A
np.corrcoef(A)[0,1]                      
# retroune les valeurs classées et leurs nombres d'apparations
V, C = np.unique(A, return_counts=True)   
# Les index des occurences pour les trier en ordre croissant
B = C.argsort()                           
# Les valeurs triées par nombre d'occurence croissant 
V[C.argsort()]                           
# V = values, C = Counts
for i,j in zip(V[C.argsort()], C[C.argsort()]): 
  # zip agrège des itérables dans un tuple
  print(f"La valeur {i} apparaît {j} fois.")   
# met un Nan dans en 4,3 dans matrice A
A[4,3]= np.nan                            
# moy avec des Nan dans la matrice
np.nanmean(A)                            
# masque booléen avec T quand y a un Nan
B = np.isnan(A)                           
# compter les Nan
NbDeNan = B.sum()                         
Qualité = NbDeNan/A.siz
# # On remplace les Nan par 0.0
A[np.isnan(A)]=0.0                       
# Algèbre linéaire
# Transposée
A.T                                       
A.dot(B)
# déterminant
np.linalg.det(A)                          
# inverse
np.linalg.inv(A)                          
# valeurs propres
np.linalg.eig(A)                         
# Broadcasting
# Etendre les dimensions d'un tableau
# REGLE : 
# les dimensions de A et B doivent être identiques
# ou alors l'une des 2 est égale à 1
# Matrice (2,3) et matrice (2,3) OK
# Matrice (2,3) et matrice (2,2) NOK
# Matrice (2,3) et matrice (2,1) OK (on transforme le 1 en
# 3. On répette à droite le motif (2,1) pour couvrir (2,3))
# Matrice (2,3) et matrice (3,1) NOK
# Matrice (4,1) et matrice (1,3) OK (on broadcast dans les 
# 2 axes
# ajoute 2 partout. scalaire == tableau 1x1
A = A + 2                                 
# A et B même shape
C = A + B                                
A = np.random.randint(0,100,(2,3))
B = np.ones((2,1))                        
# B est étendue et dupliquée à droite 2 fois (3 colonnes)  
# l'addition se fait ensuite
A+B                                       
                                         
A = np.random.randint(0,100,(2,3))
B = np.ones((1,3))
# B est étendue et dupliquée en bas 2 fois (3 lignes)
# l'addition se fait ensuite
A+B                                       
                                         
A = np.random.randint(0,100,(4,3))
B = np.ones((1,3))
A+
A = np.random.randint(0,100,(4,1))
B = np.ones((1,3))
# Matrice 4x3. 
# A est étendue en bas 2 fois (3 lignes) et le contenu de 
# la ligne est répété
# B est étendue à droite 3 fois (4 colonnes) et le contenu
# de la colonne est répété
# l'addition se fait ensuite
A+B                
# Z! broadcast intenpestifs. Utiliser reshape
A = np.random.randint(0,10,(4,1))
B = np.ones((3))
B = B.reshape(3,1

SyntaxError: invalid syntax. Perhaps you forgot a comma? (914802043.py, line 12)